openapi: 3.0.0
info:
  title: Chatroom API
  version: 1.0.0
  description: API for creating and managing chatrooms.
servers:
  - url: http://localhost:9090
    description: Local development server
paths:
  /chatrooms:
    get:
      summary: List all chatrooms
      description: Retrieve a list of all chatrooms with full details.
      operationId: listChatrooms
      tags:
        - Chatrooms
      responses:
        "200":
          description: A list of all chatrooms.
          content:
            application/json:
              schema:
                type: object
                properties:
                  chatrooms:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          description: The unique identifier of the chatroom.
                        name:
                          type: string
                          description: The name of the chatroom.
                        description:
                          type: string
                          description: A short description of the chatroom.
                        created_at:
                          type: string
                          format: date-time
                          description: The creation timestamp of the chatroom.
                        max_users:
                          type: integer
                          description: The maximum number of users allowed in the chatroom.
                        current_users:
                          type: integer
                          description: The current number of users in the chatroom.
        "500":
          description: Server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
    post:
      summary: Create a new chatroom
      description: Creates a chatroom with the specified name, description, and maximum number of users.
      operationId: createChatroom
      tags:
        - Chatrooms
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: The name of the chatroom.
                description:
                  type: string
                  description: The description of the chatroom.
                  default: ""
                max_users:
                  type: integer
                  description: Maximum number of users allowed in the chatroom.
                  default: 100
              required:
                - name
      responses:
        "201":
          description: Chatroom created successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: Unique identifier for the chatroom.
                  name:
                    type: string
                    description: Name of the chatroom.
                  description:
                    type: string
                    description: Description of the chatroom.
                  created_at:
                    type: string
                    format: date-time
                    description: Timestamp of when the chatroom was created.
                  max_users:
                    type: integer
                    description: Maximum number of users allowed in the chatroom.
                  current_users:
                    type: integer
                    description: Current number of users in the chatroom.
        "400":
          description: Bad Request - Invalid input data.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message.
        "401":
          description: Unauthorized - Missing or invalid authentication token.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message.
        "500":
          description: Internal Server Error - Unexpected server issue.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message.
      security:
        - bearerAuth: [ ]
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
